# Generated by Django 5.2.15 on 2026-08-02

from datetime import timedelta

import django.db.models.deletion
import django.utils.timezone
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def invalidate_historical_otps(apps, schema_editor):
    phone_otp = apps.get_model("accounts", "PhoneOTP")
    phone_otp.objects.all().update(
        code_hash=make_password(None),
        delivery_status="failed",
        invalidated_at=django.utils.timezone.now(),
    )


def restore_inert_legacy_otps(apps, schema_editor):
    phone_otp = apps.get_model("accounts", "PhoneOTP")
    phone_otp.objects.all().update(
        code="000000",
        is_used=True,
        expires_at=django.utils.timezone.now() - timedelta(days=1),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="phoneotp",
            name="phone_otp_lookup_idx",
        ),
        migrations.AlterField(
            model_name="phoneotp",
            name="code",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="code_hash",
            field=models.CharField(default="", editable=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("uncertain", "Uncertain"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="invalidated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="pending_email",
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="pending_first_name",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="pending_last_name",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="pending_password_hash",
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_otps",
                to="accounts.user",
            ),
        ),
        migrations.RunPython(
            invalidate_historical_otps,
            restore_inert_legacy_otps,
        ),
        migrations.RemoveField(
            model_name="phoneotp",
            name="code",
        ),
        migrations.AddIndex(
            model_name="phoneotp",
            index=models.Index(
                fields=[
                    "phone_number",
                    "purpose",
                    "delivery_status",
                    "-created_at",
                ],
                name="phone_otp_lookup_idx",
            ),
        ),
        migrations.CreateModel(
            name="LoginThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier_hash", models.CharField(max_length=64, unique=True)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("window_started_at", models.DateTimeField()),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
    ]
