# Generated by Django 5.2.15 on 2026-06-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stock_reduced",
            field=models.BooleanField(default=False),
        ),
    ]
