# Generated by Django 5.2.15 on 2026-06-14 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_stock_reduced"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed", "Fixed")],
                        max_length=20,
                    ),
                ),
                ("discount_value", models.PositiveIntegerField()),
                (
                    "max_discount_amount",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("min_order_amount", models.PositiveIntegerField(default=0)),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_amount",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="orders.coupon",
            ),
        ),
    ]
