# Generated by Django 5.2.15 on 2026-06-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_coupon_order_discount_amount_order_shipping_cost_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_type", "fixed"),
                    ("discount_value__lte", 100),
                    _connector="OR",
                ),
                name="coupon_percentage_maximum_100",
            ),
        ),
    ]
