# Generated by Django 5.2.15 on 2026-07-18 22:19

from django.db import migrations, models


def create_default_shipping_settings(apps, schema_editor):
    shipping_settings = apps.get_model("orders", "ShippingSettings")
    shipping_settings.objects.get_or_create(
        pk=1,
        defaults={
            "tabriz_shipping_fee": 50_000,
            "nationwide_shipping_fee": 50_000,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_manual_review_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_zone",
            field=models.CharField(
                blank=True,
                choices=[("tabriz", "داخل تبریز"), ("nationwide", "سایر نقاط کشور")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ShippingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tabriz_shipping_fee",
                    models.PositiveBigIntegerField(
                        default=50000, verbose_name="هزینه ارسال داخل تبریز"
                    ),
                ),
                (
                    "nationwide_shipping_fee",
                    models.PositiveBigIntegerField(
                        default=50000, verbose_name="هزینه ارسال سایر نقاط کشور"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "تنظیمات هزینه ارسال",
                "verbose_name_plural": "تنظیمات هزینه ارسال",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pk", 1)),
                        name="shipping_settings_singleton_pk",
                    )
                ],
            },
        ),
        migrations.RunPython(
            create_default_shipping_settings,
            migrations.RunPython.noop,
        ),
    ]
