# Generated by Django 5.2.16 on 2026-08-01 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_shipping_zone_shippingsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("consumed", "Consumed"),
                            ("released", "Released"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("usage_limit__isnull", True),
                    ("used_count__lte", models.F("usage_limit")),
                    _connector="OR",
                ),
                name="coupon_used_count_within_limit",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cart_item_id_snapshot",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="couponredemption",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="redemptions",
                to="orders.coupon",
            ),
        ),
        migrations.AddField(
            model_name="couponredemption",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_redemption",
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(
                fields=["coupon", "state"], name="coupon_redemption_state_idx"
            ),
        ),
    ]
