# Generated by Django 5.2.16 on 2026-09-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_coupon_per_user_usage_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="postal_tracking_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="کد رهگیری پس از تغییر وضعیت سفارش به ارسال\u200cشده برای مشتری نمایش داده می\u200cشود.",
                max_length=100,
                verbose_name="کد رهگیری پستی",
            ),
        ),
    ]
